blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    # path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

item/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'products', ItemViewSet)
router.register(r'stock-updates', StockUpdateViewSet)

app_name = 'item'

urlpatterns = [
    path('api/', include(router.urls)),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/low-stock/', LowStockListView.as_view(), name='low_stock_list'),
    path('dashboard/', InventoryDashboardView.as_view(), name='dashboard')
]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views


urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', include(('item.urls', 'item'), namespace='items')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('notadmin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name =  'users'
    
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('redirect-after-login/', views.role_based_redirect, name='role_redirect'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock title %} | {{site_name}}</title>
</head>

<body class="min-h-screen flex flex-col bg-white dark:bg-gray-900 dark:text-gray-100">

    <nav class="py-4 px-2 flex justify-between items-center border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
            <div class="flex itmes-center justify-between">
                <a href="/" class="text-2xl font-bold px-12">{{core.site_name}}</a>

                {% comment %} Hamburger Button {% endcomment %}
                <button class="md:hidden text-gray-700 dark:text-gray-200 focus:outline-none" onclick="toggleMenu()">
                    ☰
                </button>

                {% comment %} Nav Links {% endcomment %}
                <div id="nav-links" class=" md-flex space-x-4">
                    {% if user.is_authenticated %}
                        <a href="{% url "item:dashboard" %}" class="text-lg font-semibold hover:text-gray-500">Dashboard</a>
                        <a href="{% url "item:product_list" %}" class="text-lg font-semibold hover:text-gray-500">Products</a>
                        <a href="{% url "blog:post_list" %}" class="text-lg font-semibold hover:text-gray-500">Blog</a>
                        <a href="#" class="text-lg font-semibold hover:text-gray-500">Contact</a>

                        <a href="{% url "users:logout" %}" class="px-7 px-4 text-lg font-semibold bg-teal-500 text-white rounded hover:bg-teal-700">Log 
                            Out</a>
                    {% else %}
                        <a href="{% url "users:register" %}" class="px-7 px-4 text-lg font-semibold bg-teal-500 text-white rounded hover:bg-teal-700">Sign
                            Up</a>
                        <a href="{% url "users:login" %}" class="px-6 px-3 text-lg font-semibold bg-gray-500 text-white rounded hover:bg-gray-700">Log
                            In</a> 
                    {% endif %}
                </div>
            </div>

            {% comment %} Mobile nav  {% endcomment %}
            <div class="md:hidden hidden mt-4 space-x-4">
                {% if user.is_authenticated %}
                    <a href="{% url "item:dashboard" %}" class="text-lg font-semibold hover:text-gray-500">Dashboard</a>
                    <a href="{% url "item:product_list" %}" class="text-lg font-semibold hover:text-gray-500">Products</a>
                    <a href="{% url "blog:post_list" %}" class="text-lg font-semibold hover:text-gray-500">Blog</a>
                    <a href="#" class="text-lg font-semibold hover:text-gray-500">Contact</a>

                    <a href="{% url "users:register" %}" class="px-7 px-4 text-lg font-semibold bg-teal-500 text-white rounded hover:bg-teal-700">Log 
                        Out</a>
                {% else %}
                    <a href="{% url "users:register" %}" class="px-7 px-4 text-lg font-semibold bg-teal-500 text-white rounded hover:bg-teal-700">Sign
                        Up</a>
                    <a href="{% url "users:login" %}" class="px-6 px-3 text-lg font-semibold bg-gray-500 text-white rounded hover:bg-gray-700">Log
                        In</a> 
                {% endif %}
            </div>
        </div>
    </nav>

    {% comment %} Django Messages {% endcomment %}
    <div class="max-w-4xl mx-auto mt-4 px-4">
        {% if messages %}
            <ul class="space-y-2">
                {% for message in messages %}
                    <li clss="p-3 rounded text-sm
                        {% if message.tags == 'success' %}bg-green-100 text-green-800 dark:bg-green-800 dark:text-white
                        {% elif message.tags == 'warning' %}bg-yellow-100 text-yellow-800 dark:bg-yellow-700 dark:text-white
                        {% elif message.tags == 'error' %}bg-red-100 text-red-800 dark:bg-red-800 dark:text-white
                        {% endif %}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    {% comment %} Main Content Section {% endcomment %}
    <div class="flex-1 px-6 py-6 text-2xl shadow">
        {% block content %}
        {% endblock content %}
    </div>

    {% comment %} Footer Section {% endcomment %}
    <footer class="bg-gray-800 text-gray-300 dark:text-gray-300 py-6 mt-auto">
        <div class="max-w-7xl mx-auto px-4 flex flex-col md:flex-row justify-between gap-8">
            <!-- About Section -->
            <div class="md:w-2/3">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-sm text-gray-500">
                    {{about.about_text}}
                </p>
            </div>

            <!-- Menu Section -->
            <div class="md:w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-1">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Services</a></li>
                    <li><a href="mailto:{{ general_info.email }}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </div>

        <!-- Social Media Section -->
        <div class="max-w-7xl mx-auto px-4 mt-6 border-t border-gray-700 pt-4 flex justify-center space-x-6">
                <a href="{{ general_info.linkedIn_url }}" target="_blank" class="hover:text-teal-500">
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                        <path d="M19 0h-14c-2.77 0-5 2.23-5 5v14c0 2.77 2.23 
                        5 5 5h14c2.77 0 5-2.23 5-5v-14c0-2.77-2.23-5-5-5zm-11 
                        19h-3v-10h3v10zm-1.5-11.27c-.96 
                        0-1.73-.79-1.73-1.73s.77-1.73 
                        1.73-1.73 1.73.79 
                        1.73 1.73-.77 1.73-1.73 1.73zm13.5 
                        11.27h-3v-5.6c0-1.34-.03-3.07-1.87-3.07-1.87 
                        0-2.16 1.46-2.16 2.96v5.71h-3v-10h2.88v1.36h.04c.4-.75 
                        1.38-1.54 2.84-1.54 3.04 0 3.6 
                        2 3.6 4.59v5.59z"/>
                    </svg>
                </a>

                <a href="{{ general_info.github_url }}" target="_blank" class="hover:text-teal-500">
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                        <path d="M12 .5C5.65.5.5 5.65.5 12c0 
                        5.08 3.29 9.37 7.86 10.89.58.11.79-.25.79-.56 
                        0-.28-.01-1.02-.02-2-3.2.7-3.88-1.54-3.88-1.54-.53-1.35-1.3-1.71-1.3-1.71-1.06-.73.08-.72.08-.72 
                        1.17.08 1.78 1.2 1.78 1.2 1.04 1.78 2.73 1.27 3.4.97.11-.75.41-1.27.74-1.56-2.55-.29-5.23-1.27-5.23-5.65 
                        0-1.25.45-2.28 1.19-3.08-.12-.29-.52-1.45.11-3.02 0 
                        0 .98-.31 3.2 1.18a11.1 11.1 0 0 1 5.82 0c2.22-1.49 
                        3.2-1.18 3.2-1.18.63 1.57.23 2.73.11 
                        3.02.74.8 1.19 1.83 1.19 3.08 0 4.39-2.69 5.36-5.25 
                        5.64.42.36.79 1.07.79 2.16 0 1.56-.01 2.82-.01 
                        3.2 0 .31.21.67.8.56A10.51 10.51 0 0 0 23.5 12C23.5 
                        5.65 18.35.5 12 .5z"/>
                    </svg>
                </a>

                {% if general_info.twitter_url %}
                <a href="{{ general_info.twitter_url }}" target="_blank" class="hover:text-teal-500">
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                        <path d="M23 3a10.9 10.9 0 0 
                        1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 
                        10.66 0 0 1 3 4s-4 9 5 13a11.64 
                        11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 
                        4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"/>
                    </svg>
                </a>
                {% endif %}

                <a href="{{ general_info.instagram_url }}" target="_blank" class="hover:text-teal-500">
                    <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                        <path d="M7.75 2h8.5A5.75 5.75 0 0 1 
                        22 7.75v8.5A5.75 5.75 0 0 1 
                        16.25 22h-8.5A5.75 5.75 0 0 1 
                        2 16.25v-8.5A5.75 5.75 0 0 1 
                        7.75 2zm0 1.5A4.25 4.25 0 0 0 
                        3.5 7.75v8.5A4.25 4.25 0 0 0 
                        7.75 20.5h8.5a4.25 4.25 0 0 0 
                        4.25-4.25v-8.5A4.25 4.25 0 0 0 
                        16.25 3.5h-8.5zM12 7a5 5 0 1 
                        1 0 10 5 5 0 0 1 0-10zm0 1.5a3.5 
                        3.5 0 1 0 0 7 3.5 3.5 0 0 0 
                        0-7zm5.75-.88a1.13 1.13 0 1 1 
                        0 2.25 1.13 1.13 0 0 1 0-2.25z"/>
                    </svg>
                </a>
                <p>© {{ general_info.site_name }} | {{ general_info.location }}</p>
        </div>
    </footer>


    {% block javascript %}
        <script src="{% static "js/base.js" %}"></script>
    {% endblock javascript %}
</body>

</html>